version: 2
updates:
  - package-ecosystem: "maven"
    target-branch: "main"
    directory: "/"
    schedule:
      interval: "daily"
      time: "02:00"
    ignore:
      - dependency-name: "io.vavr:vavr"
        versions:
          - "1.0.0-alpha*"
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "daily"
      time: "02:00"
